CXX 		=	g++
CXXFLAGS	=	-Wall -ggdb
CC 		=	gcc
CFLAGS		=	-Wall -ggdb

OBJS = const enumeration initialization literal_constants passage_printing print_size_c print_size_cpp reference Sales_item scope typedef variables

all: $(OBJS)

clean:
	$(RM) $(OBJS)
